name: 'Discord Webhook'
on:
  issues:
    types: [ opened ]
  pull_request_target:
    types: [ opened, reopened ]
  discussion:
    types: [ created ]

jobs:
  trigger-workflow:
    uses: eclipse-edc/.github/.github/workflows/discord-webhook.yml@main
    inputs:
      event-name: ${{ github.event_name }}
      event: ${{ github.event }}
    secrets:
      envDiscord: ${{ secrets.DISCORD_WEBHOOK_GITHUB }}